//user
export const AUTHENTICATING_USER = 'AUTHENTICATING_USER'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const FAILED_LOGIN = 'FAILED_LOGIN'
export const LOG_OUT = 'LOG_OUT'

//listing
export const SELECT_LISTING = 'SELECT_LISTING'
export const ADD_LISTING = 'ADD_LISTING'
export const FETCH_LISTINGS = 'FETCH_LISTINGS'
export const ADDING_LISTING = 'ADDING_LISTING'
export const ADDED_LISTING = 'ADDED_LISTING'

//reservation
export const ADD_RESERVATION = 'ADD_RESERVATION'
export const ADDING_RESERVATION = 'ADDING_RESERVATION'
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS'
export const ADDED_RESERVATION = 'ADDED_RESERVATION'

//trips
export const FETCH_TRIPS = 'FETCH_TRIPS'
export const SET_TRIP = 'SET_TRIP'

//reviews
export const ADD_REVIEW = 'ADD_REVIEW'
export const FETCH_REVIEWS = 'FETCH_REVIEWS'
export const ADDING_REVIEW = 'ADDING_REVIEW'
export const ADDED_REVIEW = 'ADDED_REVIEW'

//neighbourhoods
export const FETCH_NEIGHBOURHOODS = 'FETCH_NEIGHBOURHOODS'
